version: '3'
services:
  db:
    image: postgres:10
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:5.0.3
    volumes:
      - redis:/data
    ports:
      - 6379
  backend: &backend
    build: ..
    volumes:
      - .:/myapp
    env_file:
      - ../.env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - ANYCABLE_WEBSOCKET_SERVER_URL=ws://anycable_go:8080/cable
    depends_on:
      - db
      - redis
  web:
    <<: *backend
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - rpc
      - anycable_go
  rpc:
    <<: *backend
    command: anycable
    restart: always
  anycable_go:
    image: 'anycable/anycable-go:v0.6.0'
    restart: always
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - REDIS_URL=redis://redis:6379/0
      - ANYCABLE_RPC_HOST=rpc:50051
    depends_on:
      - redis
      - rpc

volumes:
  postgres:
  redis: