version: '3'
services:
  ghost:
    ports:
      - 80:2368
    logging:
      driver: awslogs
      options:
        awslogs-group: blog
        awslogs-region: eu-west-3
        awslogs-stream-prefix: ghost
    links:
      - ghost_db:ghost_db
  ghost_db:
    logging:
      driver: awslogs
      options:
        awslogs-group: blog
        awslogs-region: eu-west-3
        awslogs-stream-prefix: mysql
