version: '3'
services:
  rocketchat_db:
    image: mongo:3.0
    command: mongod --smallfiles
    volumes:
      - rocketchat_db_db:/data/db
      - rocketchat_db_dump:/dump
  rocketchat:
    image: rocketchat/rocket.chat:latest
    environment:
      - MONGO_URL=mongodb://rocketchat_db:27017/rocketchat
      - ROOT_URL=https://192.168.99.100
      - Accounts_UseDNSDomainCheck=True
    ports:
      - 3001:3000
    depends_on:
      - rocketchat_db

volumes:
  rocketchat_db_db:
  rocketchat_db_dump: